# Generated by Django 5.2 on 2025-06-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Detail',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.URLField(blank=True)),
                ('companyname', models.CharField(max_length=100)),
                ('companyphone', models.IntegerField(max_length=10)),
                ('gmail', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.IntegerField()),
                ('confirm_password', models.IntegerField()),
            ],
        ),
    ]
