# Generated by Django 5.2 on 2025-06-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='confirm_password',
        ),
        migrations.AddField(
            model_name='user_detail',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='companyphone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='gmail',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='user_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
